-- Project archive/restore is non-destructive. This append-only table keeps the authorization
-- reason and the exact task-status snapshot that was observed while the project row was locked.
CREATE TABLE project_audit (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id          BIGINT NOT NULL,
    action              VARCHAR(20) NOT NULL,
    reason              TEXT NOT NULL,
    todo_count          BIGINT NOT NULL,
    in_progress_count   BIGINT NOT NULL,
    blocked_count       BIGINT NOT NULL,
    done_count          BIGINT NOT NULL,
    occurred_at         TIMESTAMP NOT NULL,
    CONSTRAINT fk_project_audit_project FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT ck_project_audit_action CHECK (action IN ('ARCHIVED', 'RESTORED'))
);

CREATE INDEX idx_project_audit_project_id_id ON project_audit (project_id, id);
