-- Standard-SQL identity columns (BIGINT + GENERATED BY DEFAULT AS IDENTITY).
-- Portable to MySQL by changing only this file: replace the identity clause
-- with `AUTO_INCREMENT`, per the R3 portability requirement.
CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    title VARCHAR(300) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'TODO',
    category VARCHAR(30),
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_task_project FOREIGN KEY (project_id) REFERENCES project (id)
);

CREATE INDEX idx_task_project_status ON task (project_id, status);

CREATE TABLE task_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    from_status VARCHAR(20),
    to_status VARCHAR(20) NOT NULL,
    note TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_task_log_task FOREIGN KEY (task_id) REFERENCES task (id)
);
