-- role 表：角色的工作指引集中存放在看板，Claude 與 Codex 共用同一份。
-- 兩層設計：project_id 為 NULL 代表通用指引；指定 project_id 代表該專案的覆寫版本。
--
-- 標準 UNIQUE 索引把 NULL 視為互不相等（已用 H2 實測驗證），因此
-- UNIQUE(name, project_id) 擋不住「同一個通用角色（project_id 皆為 NULL）」重複。
-- 用 GENERATED ALWAYS AS 產生一個不可為 NULL 的 project_scope 欄位
-- （通用指引固定映射為 0，專案 id 從 1 起跳，不會與之衝突），
-- 對這個欄位建 UNIQUE 索引即可同時涵蓋「通用層不可重複」與「同專案同名不可重複」。
CREATE TABLE role (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(60) NOT NULL,
    category        VARCHAR(30),
    instructions    TEXT,
    project_id      BIGINT,
    project_scope   BIGINT GENERATED ALWAYS AS (COALESCE(project_id, 0)) NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL,
    CONSTRAINT fk_role_project
        FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE,
    CONSTRAINT uk_role_name_project UNIQUE (name, project_scope)
);

CREATE INDEX idx_role_project ON role (project_id);
