-- #113 結構化 BLOCKED 流程。
--
-- task_block_event 是 append-only 的 audit 記錄：每次呼叫 block_task 都新增一列，
-- 解除阻塞（任務轉出 BLOCKED）時只更新該列的 cleared_at，不刪除、不覆寫既有欄位，
-- 確保完整歷史快照可回溯。
--
-- 這張表與既有的 task_dependency（任務相依，用於 claim_next_task 的前置守衛）
-- 是不同語意：task_dependency 表達「任務 A 必須等任務 B 完成才能被認領」，
-- 是規劃階段就存在、跟任務是否卡住無關的固定關係；task_block_event 表達的是
-- 「這次 BLOCKED 事件當下，agent 聲稱自己在等哪些任務」，屬於執行期間的快照，
-- 兩者互不影響、也不共用同一張表。
CREATE TABLE task_block_event (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id             BIGINT NOT NULL,
    reason_type         VARCHAR(30) NOT NULL,
    detail              TEXT NOT NULL,
    blocked_by          VARCHAR(60) NOT NULL,
    blocked_at          TIMESTAMP NOT NULL,
    cleared_at          TIMESTAMP,
    CONSTRAINT fk_task_block_event_task
        FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE
);

CREATE INDEX idx_task_block_event_task ON task_block_event (task_id);

-- 一次 block 事件可以關聯多個「正在等待」的任務（僅 DEPENDENCY 原因會有資料）。
-- 刻意不重用 task_dependency：那張表的每一列代表恆常的相依關係，
-- 這裡的每一列只是某次 block 事件的快照，事件本身結束後仍完整保留供追溯。
CREATE TABLE task_block_dependency (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_event_id      BIGINT NOT NULL,
    blocking_task_id    BIGINT NOT NULL,
    CONSTRAINT fk_task_block_dependency_event
        FOREIGN KEY (block_event_id) REFERENCES task_block_event (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_block_dependency_blocking_task
        FOREIGN KEY (blocking_task_id) REFERENCES task (id) ON DELETE CASCADE
);

CREATE INDEX idx_task_block_dependency_event ON task_block_dependency (block_event_id);

-- Task 上快取「目前」有效的 block event，供 list/filter 直接讀取，不必每次都
-- 找最新一筆 task_block_event。離開 BLOCKED 狀態時清空這個指標（該筆 event 的
-- cleared_at 會被同時填上），但 task_block_event 本身的列永久保留。
ALTER TABLE task ADD COLUMN current_block_event_id BIGINT;
ALTER TABLE task
    ADD CONSTRAINT fk_task_current_block_event
        FOREIGN KEY (current_block_event_id) REFERENCES task_block_event (id);
