-- #114 complete_task 與完成證據。
--
-- task_completion_evidence 是 append-only 的 audit 記錄：每次成功呼叫 complete_task
-- 都新增一列，不覆寫、不刪除既有列。任務重開（DONE -> IN_PROGRESS）後再次完成，
-- 會再新增一列新的 evidence，舊 evidence 永久保留供追溯，因此同一任務可能對應
-- 多筆 evidence，查詢時以 completed_at 排序取最新一筆即為「目前的完成證據」。
--
-- 這是 agent 自行聲明的完成證據，不代表 server 已經驗證過外部 repo 的 commit
-- 或實際執行過任何指令；commit_ref／changed_files 僅原樣記錄呼叫端提供的內容。
CREATE TABLE task_completion_evidence (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id             BIGINT NOT NULL,
    summary             TEXT NOT NULL,
    changed_files       TEXT,
    commit_ref          VARCHAR(200),
    completed_by        VARCHAR(60) NOT NULL,
    completed_at        TIMESTAMP NOT NULL,
    CONSTRAINT fk_task_completion_evidence_task
        FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE
);

CREATE INDEX idx_task_completion_evidence_task ON task_completion_evidence (task_id);

-- 一次完成證據至少要附一筆驗證結果；result 限定 PASSED/FAILED/NOT_RUN，
-- 由應用層驗證（FAILED 不可完成、NOT_RUN 必須有 detail 說明原因），
-- 資料庫層只保留最基本的 NOT NULL 約束。
CREATE TABLE task_completion_verification (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_id         BIGINT NOT NULL,
    name                VARCHAR(200) NOT NULL,
    result              VARCHAR(20) NOT NULL,
    detail              TEXT,
    CONSTRAINT fk_task_completion_verification_evidence
        FOREIGN KEY (evidence_id) REFERENCES task_completion_evidence (id) ON DELETE CASCADE
);

CREATE INDEX idx_task_completion_verification_evidence ON task_completion_verification (evidence_id);
